name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        env: 
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME}}/calculadora-front:latest .

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/calculadora-front:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Railway
        env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -X POST "https://backboard.railway.app/v2/deploy" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN}}" \
            -d '{
              "service": "frontend",
              "image": "${{ secrets.DOCKERHUB_USERNAME}}/calculadora-front:latest"
            }'
